name: Test OSX

on: push

jobs:
  test:
    name: Test MacUp config
    runs-on:  macos-latest # macOS Monterey 12.6.9
    steps:
      - name: Virtual env info
        run: |
          system_profiler SPSoftwareDataType
      - name: Create workspace
        run: |
          mkdir -p ~/.macup; cd ~/.macup;
      - name: Fetch Commit
        run: |
          curl -L "https://github.com/mikeguta/macup/tarball/${GITHUB_SHA}" | tar -xzv --strip-components 1 &> /dev/null;
      - name: Install and Run MacUp
        run: |
          # Setup Test env
          defaults write -g AppleLanguages '("en-GB")';
          export TERM=xterm-256color;
          export MACUP_ENV="development";
          export GIT_USERNAME="tester"
          export GIT_EMAIL="tester@example.com"

          # Install
          sh bootstrap.sh
